### ISSUE TITLE
Can't use back button on {lang}/what or refresh on {lang}/go pages

### ISSUE THREAD

**Issue by wkmor1** [luomus/iratebirds#8]
This only seems to be a problem on the live version. Doesn't happen when you run the app locally.

**Comment by vixriihi** [comment]
nginx should be configured so that all requests (other than api) point to index.html :)

**Comment by wkmor1** [comment]
Hmm I wonder if that is possible with netllfy?

**Comment by wkmor1** [comment]
Perhaps this is what we need? https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file
